use proc_macro::TokenStream;
use syn::{ItemImpl, ItemStruct, parse_macro_input};

mod builder;
mod generics;
mod methods;
mod registry;

/// Turns a plain struct into a typestate builder.
///
/// Fields can be annotated with `#[stave(required)]` or
/// `#[stave(optional)]`. Fields without either annotation are treated as
/// optional. Optional fields are simply wrapped in `Option<T>`.
///
/// For each required field, `#[builder]` generates two hidden marker types -
/// one representing the field being unset, one representing it being set and
/// carrying the field's value - and adds a corresponding generic parameter to
/// the struct. A field's value can only be read once its marker type proves
/// it has been set; see the `#[methods]` macro for how that state is
/// threaded through and queried.
///
/// A `new()` constructor is generated, returning the struct with every
/// required field in its unset state and every optional field set to `None`.
///
/// ```rust
/// use std::time::Duration;
/// use stave_macros::builder;
///
/// #[builder]
/// struct Server {
///     #[stave(required)]
///     host: String,
///     #[stave(required)]
///     port: u16,
///     #[stave(optional)]
///     timeout: Duration,
/// }
///
/// let server = Server::new();
/// ```
///
/// The struct's own generic parameters (lifetimes, type parameters, const
/// parameters) are preserved, and the generated marker types are themselves
/// parameterized over whichever of those parameters the corresponding field's
/// type actually uses.
#[proc_macro_attribute]
pub fn builder(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let input = parse_macro_input!(item as ItemStruct);

    builder::expand(input)
        .unwrap_or_else(|err| err.write_errors())
        .into()
}

/// Enriches an `impl` block for a struct annotated with `#[builder]`, enabling
/// state-dependent methods and generating boilerplate field setters.
///
/// Within the `impl` block, methods can leverage two specialized attributes to
/// manage the compile-time typestate lifecycle:
///
/// # Attributes
///
/// * `#[sets(field_name)]`: Designates a method as the setter for a specific
///   field. The method body computes and returns the raw inner field type rather
///   than the parent struct. `#[methods]` automatically rewrites the method
///   signature to execute the typestate transition, consuming the current state
///   by value and returning `Self` parameterized with the updated set marker.
///   For any field that does not explicitly receive a custom `#[sets(...)]`
///   method, a public default setter named `set_{field_name}` is automatically
///   synthesized.
/// * `#[requires(field_a, field_b, ...)]`: Restricts the availability of a
///   method until all specified required fields have been initialized. Within
///   the scope of the method, stave guarantees the listed fields are populated,
///   allowing safe data access via generated getters. This can be applied to
///   any arbitrary, user-defined function to enforce state requirements at
///   compile time.
///
/// # Reentrancy and Signatures
///
/// Custom setters for required fields must take `self` or `mut self` by value,
/// because the underlying type representation of the struct structurally alters
/// upon field initialization. You can combine `#[sets(...)]` and `#[requires(...)]`
/// on a single method to build sequential initialization dependencies.
///
/// # Automatically Generated Getters
///
/// stave automatically synthesizes reference-based getters named after each field.
/// Required field getters are only exposed and accessible on the struct once their
/// corresponding typestate transitions to a set state. Optional field getters
/// return an `&Option<T>` and remain accessible throughout the entire lifecycle
/// of the builder.
///
/// # Examples
///
/// ```rust
/// # use stave_macros::{builder, methods};
/// # #[builder]
/// # struct Server { #[stave(required)] host: String, #[stave(required)] port: u16 }
/// #[methods]
/// impl Server {
///     #[sets(host)]
///     fn set_host(self, value: impl Into<String>) -> String {
///         value.into()
///     }
///
///     // This user-defined method is only callable once host and port are set.
///     #[requires(host, port)]
///     fn finish(self) -> String {
///         format!("{}:{}", self.host(), self.port())
///     }
/// }
///
/// let endpoint = Server::new()
///     .set_host("localhost")
///     .set_port(8080) // set_port is automatically generated by the macro
///     .finish();
/// ```
#[proc_macro_attribute]
pub fn methods(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let input = parse_macro_input!(item as ItemImpl);

    methods::expand(input)
        .unwrap_or_else(|err| err.write_errors())
        .into()
}
